/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SobreImport } from './routes/sobre'
import { Route as RegistarImport } from './routes/registar'
import { Route as PerfilImport } from './routes/perfil'
import { Route as PainelGestorMesasImport } from './routes/painelGestorMesas'
import { Route as PainelGestorJogosImport } from './routes/painelGestorJogos'
import { Route as PainelGestorImport } from './routes/painelGestor'
import { Route as PainelAdminImport } from './routes/painelAdmin'
import { Route as LoginImport } from './routes/login'
import { Route as CafesImport } from './routes/cafes'
import { Route as IndexImport } from './routes/index'
import { Route as CafeCafeIdImport } from './routes/cafe/$cafeId'

// Create/Update Routes

const SobreRoute = SobreImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRoute,
} as any)

const RegistarRoute = RegistarImport.update({
  id: '/registar',
  path: '/registar',
  getParentRoute: () => rootRoute,
} as any)

const PerfilRoute = PerfilImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRoute,
} as any)

const PainelGestorMesasRoute = PainelGestorMesasImport.update({
  id: '/painelGestorMesas',
  path: '/painelGestorMesas',
  getParentRoute: () => rootRoute,
} as any)

const PainelGestorJogosRoute = PainelGestorJogosImport.update({
  id: '/painelGestorJogos',
  path: '/painelGestorJogos',
  getParentRoute: () => rootRoute,
} as any)

const PainelGestorRoute = PainelGestorImport.update({
  id: '/painelGestor',
  path: '/painelGestor',
  getParentRoute: () => rootRoute,
} as any)

const PainelAdminRoute = PainelAdminImport.update({
  id: '/painelAdmin',
  path: '/painelAdmin',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CafesRoute = CafesImport.update({
  id: '/cafes',
  path: '/cafes',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CafeCafeIdRoute = CafeCafeIdImport.update({
  id: '/cafe/$cafeId',
  path: '/cafe/$cafeId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cafes': {
      id: '/cafes'
      path: '/cafes'
      fullPath: '/cafes'
      preLoaderRoute: typeof CafesImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/painelAdmin': {
      id: '/painelAdmin'
      path: '/painelAdmin'
      fullPath: '/painelAdmin'
      preLoaderRoute: typeof PainelAdminImport
      parentRoute: typeof rootRoute
    }
    '/painelGestor': {
      id: '/painelGestor'
      path: '/painelGestor'
      fullPath: '/painelGestor'
      preLoaderRoute: typeof PainelGestorImport
      parentRoute: typeof rootRoute
    }
    '/painelGestorJogos': {
      id: '/painelGestorJogos'
      path: '/painelGestorJogos'
      fullPath: '/painelGestorJogos'
      preLoaderRoute: typeof PainelGestorJogosImport
      parentRoute: typeof rootRoute
    }
    '/painelGestorMesas': {
      id: '/painelGestorMesas'
      path: '/painelGestorMesas'
      fullPath: '/painelGestorMesas'
      preLoaderRoute: typeof PainelGestorMesasImport
      parentRoute: typeof rootRoute
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilImport
      parentRoute: typeof rootRoute
    }
    '/registar': {
      id: '/registar'
      path: '/registar'
      fullPath: '/registar'
      preLoaderRoute: typeof RegistarImport
      parentRoute: typeof rootRoute
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreImport
      parentRoute: typeof rootRoute
    }
    '/cafe/$cafeId': {
      id: '/cafe/$cafeId'
      path: '/cafe/$cafeId'
      fullPath: '/cafe/$cafeId'
      preLoaderRoute: typeof CafeCafeIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cafes': typeof CafesRoute
  '/login': typeof LoginRoute
  '/painelAdmin': typeof PainelAdminRoute
  '/painelGestor': typeof PainelGestorRoute
  '/painelGestorJogos': typeof PainelGestorJogosRoute
  '/painelGestorMesas': typeof PainelGestorMesasRoute
  '/perfil': typeof PerfilRoute
  '/registar': typeof RegistarRoute
  '/sobre': typeof SobreRoute
  '/cafe/$cafeId': typeof CafeCafeIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cafes': typeof CafesRoute
  '/login': typeof LoginRoute
  '/painelAdmin': typeof PainelAdminRoute
  '/painelGestor': typeof PainelGestorRoute
  '/painelGestorJogos': typeof PainelGestorJogosRoute
  '/painelGestorMesas': typeof PainelGestorMesasRoute
  '/perfil': typeof PerfilRoute
  '/registar': typeof RegistarRoute
  '/sobre': typeof SobreRoute
  '/cafe/$cafeId': typeof CafeCafeIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cafes': typeof CafesRoute
  '/login': typeof LoginRoute
  '/painelAdmin': typeof PainelAdminRoute
  '/painelGestor': typeof PainelGestorRoute
  '/painelGestorJogos': typeof PainelGestorJogosRoute
  '/painelGestorMesas': typeof PainelGestorMesasRoute
  '/perfil': typeof PerfilRoute
  '/registar': typeof RegistarRoute
  '/sobre': typeof SobreRoute
  '/cafe/$cafeId': typeof CafeCafeIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cafes'
    | '/login'
    | '/painelAdmin'
    | '/painelGestor'
    | '/painelGestorJogos'
    | '/painelGestorMesas'
    | '/perfil'
    | '/registar'
    | '/sobre'
    | '/cafe/$cafeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cafes'
    | '/login'
    | '/painelAdmin'
    | '/painelGestor'
    | '/painelGestorJogos'
    | '/painelGestorMesas'
    | '/perfil'
    | '/registar'
    | '/sobre'
    | '/cafe/$cafeId'
  id:
    | '__root__'
    | '/'
    | '/cafes'
    | '/login'
    | '/painelAdmin'
    | '/painelGestor'
    | '/painelGestorJogos'
    | '/painelGestorMesas'
    | '/perfil'
    | '/registar'
    | '/sobre'
    | '/cafe/$cafeId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CafesRoute: typeof CafesRoute
  LoginRoute: typeof LoginRoute
  PainelAdminRoute: typeof PainelAdminRoute
  PainelGestorRoute: typeof PainelGestorRoute
  PainelGestorJogosRoute: typeof PainelGestorJogosRoute
  PainelGestorMesasRoute: typeof PainelGestorMesasRoute
  PerfilRoute: typeof PerfilRoute
  RegistarRoute: typeof RegistarRoute
  SobreRoute: typeof SobreRoute
  CafeCafeIdRoute: typeof CafeCafeIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CafesRoute: CafesRoute,
  LoginRoute: LoginRoute,
  PainelAdminRoute: PainelAdminRoute,
  PainelGestorRoute: PainelGestorRoute,
  PainelGestorJogosRoute: PainelGestorJogosRoute,
  PainelGestorMesasRoute: PainelGestorMesasRoute,
  PerfilRoute: PerfilRoute,
  RegistarRoute: RegistarRoute,
  SobreRoute: SobreRoute,
  CafeCafeIdRoute: CafeCafeIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/cafes",
        "/login",
        "/painelAdmin",
        "/painelGestor",
        "/painelGestorJogos",
        "/painelGestorMesas",
        "/perfil",
        "/registar",
        "/sobre",
        "/cafe/$cafeId"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/cafes": {
      "filePath": "cafes.jsx"
    },
    "/login": {
      "filePath": "login.jsx"
    },
    "/painelAdmin": {
      "filePath": "painelAdmin.jsx"
    },
    "/painelGestor": {
      "filePath": "painelGestor.jsx"
    },
    "/painelGestorJogos": {
      "filePath": "painelGestorJogos.jsx"
    },
    "/painelGestorMesas": {
      "filePath": "painelGestorMesas.jsx"
    },
    "/perfil": {
      "filePath": "perfil.jsx"
    },
    "/registar": {
      "filePath": "registar.jsx"
    },
    "/sobre": {
      "filePath": "sobre.jsx"
    },
    "/cafe/$cafeId": {
      "filePath": "cafe/$cafeId.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
